<input type="hidden" id="user_data" value=<?php echo $_SESSION['user_id']; ?>>
<body>
    <main class="container-fluid h-100">
        <div class="row justify-content-center h-100">
            <div class="col-md-4 col-xl-3 chat">
                <div class="card mb-sm-3 mb-md-0 contacts_card">
                    <div class="card-header">
                        <div class="input-group">
                            <select id="search" class="js-select2 form-control" name="user">
                                <!-- меню из JS -->
                            </select>
                            <div class="input-group-prepend">
                                <span id="add_btn" class="input-group-text search_btn"><i class="fas fa-plus-circle"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="card-body contacts_body">
                        <ui id="chatListContainer" class="contacts">
                            <!-- меню из JS -->  
                        </ui>
                    </div>
                    <div class="card-body contacts_body">
                        <ui id="groupListContainer" class="contacts">
                            <!-- меню из JS -->
                        </ui>                       
                    </div>
                <div class="card-footer"></div>
            </div></div>
            <div class="col-md-8 col-xl-6 chat">
                <div class="card">
                    <div class="card-header msg_head">
                        <div class="d-flex bd-highlight">
                            <div class="img_cont">
                                <img id="hes_avatar" src="/img/avatar_default.jpg" class="rounded-circle user_img">
                                <span class="online_icon"></span>
                            </div>
                            <div class="user_info">
                                <span id="name-chat" data-chat-id="">Chat with GOD</span>
                                <p id="msg_count">XXX Messages</p>
                            </div>
                            <div class="audio">
                                <span><i class="fas fa-bell"></i></span>
                                <span><i class="fas fa-bell-slash"></i></span>
							</div>
                        </div>
                        <span id="action_menu_btn"><i class="fas fa-ellipsis-v"></i></span>
                        <div class="action_menu">
                            <ul>
                                <li id="profile"><i class="fas fa-user-circle"></i> Профиль</li>
                                <li id="setting"><i class="fas fa-wrench"></i> Настройки</li>
                                <li id="create"><i class="fas fa-users"></i> Создать группу</li>
                                <li id="exit"><i class="fas fa-times"></i> Выйти </a></li>
                            </ul>
                        </div>
                    </div>
                    <div id="messages-container" class="card-body msg_card_body">
                        <!-- сообщения из JS -->
                    </div>
                    <div class="card-footer">
                        <div class="input-group">
                            <textarea name="message" id="message" class="form-control type_msg" placeholder="Type your message..."></textarea>
                            <div class="input-group-append">
                                <span class="input-group-text send_btn"><i id="send-message" class="fas fa-paper-plane"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="popups__inner">
            <div class="popup profile__popup">
                <div class="container_login">
                    <div class="d-flex justify-content-center h-100">
                        <div class="card_login">
                            <a class="close_popup"><span class="text">&#10006</span></a>
                            <div class="card-header justify-content-center">
                                <h4 class="">
                                    Мой Профиль
                                </h4>
				            </div>
                            <div class="card-body">
                                <form id="profile_change" enctype="multipart/form-data">
                                    <div class="d-flex flex-column justify-content-center align-items-center h-100">
                                        <h5 class="text">Ваш Аватар</h5>
                                        <div class="img_cont_profile">
                                            <img src="/img/avatar_default.jpg" class="rounded-circle user_img_profile">
                                        </div>                                        
						            </div>
                                    <div class="card-body">
                                        <input type="hidden" name="MAX_FILE_SIZE" value="<?php echo MAX_FILE_SIZE ?>">
                                        <label for="file" class="text">Выбор Аватара для загрузки:</label>
                                        <input class="text" type="file" name="file" required accept=".jpg, .jpeg, .png, .tiff">
                                        <div><p class="text">
                                            Максимальный размер файла: <?php echo MAX_FILE_SIZE / 1000000; ?>Мб.
                                            Допустимые форматы:<?php echo '<br>' . implode(', ', ALLOWED_TYPES) ?>.            
                                        </p></div>
                                    </div>
                                    <div class="form-group">
							            <input type="submit" value="Загрузить" class="btn float-right regist_btn">
						            </div>
					            </form>
			                </div>
                        </div>
                    </div>
                </div>
            </div>
			<div class="popup setting__popup">
                <div class="container_login">
                    <div class="d-flex justify-content-center h-100" >
                        <div class="card_login">
                            <a class="close_popup"><span class="text">&#10006</span></a>
                            <div class="card-header justify-content-center">
                                <h4 class="">
                                    Настройки Профиля
                                </h4>
				            </div>
                            <div class="card-body">
                                <form method="post" action="">
                                    <h5 class="text">Ваш Ник: <span id="nick">Nickname</span></h5>
                                    <div class="input-group form-group">                                        
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-user-circle"></i></span>
                                        </div>
                                        <input id="newNick" type="text" class="form-control" placeholder="Выбрать Никнейм" name="nickname">
						            </div>
                                    <div  class="row align-items-center remember">
							            <input id="hideEmail" type="checkbox">Скрыть Email
						            </div>
                                    <div class="form-group">
							            <input id="nickChange" type="submit" value="Сохранить" class="btn float-right regist_btn">
						            </div>
					            </form>
			                </div>
                        </div>
                    </div>
                </div>
			</div>
			<div class="popup create__popup">
                <div class="container_login">
                    <div class="d-flex justify-content-center h-100" >
                        <div class="card_login">
                            <a class="close_popup"><span class="text">&#10006</span></a>
                            <div class="card-header justify-content-center">
                                <h4 class="">
                                    Создать Группу
                                </h4>
				            </div>
                            <div class="card-body">
                                <form id="group_create" method="post" action="">
                                    <div class="input-group form-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-users"></i></span>
                                        </div>
                                        <input type="text" class="form-control" placeholder="Название группы" name="groupname" required>
						            </div>
                                    <div class="checkselect" id="creategroups">
                                        <!-- меню из JS -->
                                    </div>
                                    <div class="form-group">
							            <input type="submit" value="Создать" class="btn float-right regist_btn">
						            </div>
					            </form>
			                </div>
                        </div>
                    </div>
                </div>
			</div>
		</div>
    </main>
</body>